# Generated by Django 5.1.2 on 2024-12-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_total', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('codigo_unspsc', models.CharField(blank=True, max_length=255, null=True)),
                ('rubro', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_rubro', models.TextField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('subgrupo', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('pertenece_a_la_oasti', models.CharField(blank=True, max_length=255, null=True)),
                ('area_pertenece', models.CharField(blank=True, max_length=255, null=True)),
                ('anio_paa', models.IntegerField(blank=True, null=True)),
                ('linea_paa', models.CharField(blank=True, max_length=255, null=True)),
                ('contratado_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adjudicado', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('apoyo_supervision', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_designacion_supervision', models.DateField(blank=True, null=True)),
                ('impacto', models.CharField(blank=True, max_length=255, null=True)),
                ('sistema_publicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_contratista', models.CharField(blank=True, max_length=255, null=True)),
                ('objeto', models.TextField(blank=True, null=True)),
                ('numero_proceso', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_suscripcion_contrato', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion_poliza', models.DateField(blank=True, null=True)),
                ('fecha_inicio_ejecucion', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('fecha_inicio_servicio', models.DateField(blank=True, null=True)),
                ('fecha_final_servicio', models.DateField(blank=True, null=True)),
                ('fuente_vigencia', models.CharField(blank=True, max_length=255, null=True)),
                ('modalidad_presentacion_general_cuadro', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_proceso', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total_inicial_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valor_adiciones_reducciones', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valor_total_final_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valor_antes_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valor_asignado_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valor_despues_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valor_total_asignado_paa_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('diferencia_contratado_respecto_paa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('liberaciones_cdp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cantidad_pagos_2024_hasta_31_julio', models.IntegerField(blank=True, null=True)),
                ('valor_ejecutado_2024_hasta_31_julio', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pago_mensual_aproximado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('porcentaje_ejecucion_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('presupuesto_pendiente_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expediente_gestion_documental', models.CharField(blank=True, max_length=255, null=True)),
                ('url_secop_tv', models.URLField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
