# Generated by Django 5.1.2 on 2024-10-25 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Sub-Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sub-Grupo de Mantenimiento',
                'verbose_name_plural': 'Sub-Grupos de Mantenimiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=50, verbose_name='Ítem')),
                ('element', models.CharField(max_length=200, verbose_name='Elemento')),
                ('activity', models.TextField(blank=True, verbose_name='Actividad')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('maintenance_type', models.CharField(choices=[('preventive_logic', 'Preventivo Lógico'), ('preventive_physical', 'Preventivo Físico'), ('preventive_both', 'Preventivo Físico y Lógico'), ('corrective', 'Correctivo')], max_length=50, verbose_name='Tipo de Mantenimiento')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Contrato')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio del Contrato')),
                ('contract_duration', models.CharField(blank=True, max_length=200, verbose_name='Vigencia del Contrato')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='Responsable Proveedor')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Última fecha de mantenimiento')),
                ('oasti_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_items', to=settings.AUTH_USER_MODEL, verbose_name='Responsable OASTI')),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.maintenancesubgroup', verbose_name='Sub-Grupo')),
            ],
            options={
                'verbose_name': 'Item de Mantenimiento',
                'verbose_name_plural': 'Items de Mantenimiento',
                'ordering': ['sub_group', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024, verbose_name='Año')),
                ('month', models.IntegerField(default=10, verbose_name='Mes')),
                ('week', models.IntegerField(default=1, verbose_name='Semana')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Programado')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Realización')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='maintenance.maintenanceitem', verbose_name='Item')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_updates', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Programación de Mantenimiento',
                'verbose_name_plural': 'Programaciones de Mantenimiento',
                'ordering': ['year', 'month', 'week'],
                'unique_together': {('item', 'year', 'month', 'week')},
            },
        ),
    ]
