# Generated by Django 5.1.2 on 2024-11-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='month',
            field=models.IntegerField(default=11, verbose_name='Mes'),
        ),
    ]
