# Generated by Django 5.1.2 on 2024-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenanceschedule_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='month',
            field=models.IntegerField(default=12, verbose_name='Mes'),
        ),
    ]
