# Generated by Django 5.1.2 on 2025-02-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenanceitem_oasti_responsible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='month',
            field=models.IntegerField(default=2, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Año'),
        ),
    ]
