# Generated by Django 5.1.2 on 2024-10-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Línea')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Línea Estratégica',
                'verbose_name_plural': 'Líneas Estratégicas',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarea/Meta', 'verbose_name_plural': 'Tareas/Metas'},
        ),
        migrations.AddField(
            model_name='task',
            name='alert_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha alarma'),
        ),
        migrations.AddField(
            model_name='task',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='task',
            name='deliverable',
            field=models.TextField(blank=True, verbose_name='Entregable/Acción'),
        ),
        migrations.AddField(
            model_name='task',
            name='evidence',
            field=models.TextField(blank=True, verbose_name='Evidencia'),
        ),
        migrations.AddField(
            model_name='task',
            name='limit_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mes límite'),
        ),
        migrations.AddField(
            model_name='task',
            name='support_team',
            field=models.TextField(blank=True, verbose_name='Apoya'),
        ),
        migrations.AddField(
            model_name='task',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Cumplido'), ('delayed', 'Retrasado')], default='pending', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título/Meta'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Cumplido'), ('delayed', 'Retrasado')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='task',
            name='strategic_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.strategicline', verbose_name='Línea Estratégica'),
        ),
    ]
