# Generated by Django 5.1.2 on 2024-11-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_strategicline_alter_task_options_task_alert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En Proceso'), ('Cumplido', 'Cumplido')], default='pending', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=900, verbose_name='Título/Meta'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En Proceso'), ('Cumplido', 'Cumplido')], max_length=50, verbose_name='Estado'),
        ),
    ]
