# Generated by Django 5.1.2 on 2024-11-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_area_leader_remove_task_support_team_alter_task_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='daruma_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Daruma'),
        ),
    ]
